name: Andrid Native

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select OS-platform'
        required: true
        default: 'android_native'
#   schedule:
    # android_native
#     - cron: '10 9 * * *'
    
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   repository_dispatch:
#     types: [automation]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix: 
        api-level: [29]
        target: [default]

    steps:
      - name: (From Cron) ANDROID-NATIVE
        if: github.event.schedule == '10 9 * * *'
        run: echo "PLATFORM=android_native" >> $GITHUB_ENV
        
      - name: print selected platform
        run: echo "selected platform for test = ${{ env.PLATFORM }}"

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.MOBILE_AUTO }}
          workflow: build-app-workflow.yml
          name: 100ms-app-debug.apk
          repo: 100mslive/android-build-dogfooding
          
      - name: run
        run: pwd
        
      # Run test in the above selected region
      - uses: actions/checkout@v3
      - name: Set up JDK 16
        uses: actions/setup-java@v3.2.0
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '11'

      - name: Install and Run Appium Server
        run: |
            npm install -g appium@v1.22.2
            appium -v
            appium &>/dev/null &
            ls
      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.23.0
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: mvn clean test -Dsurefire.suiteXmlFiles=${{ env.PLATFORM }}.xml
  

